name: our_mediapipe_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bitmap: ^0.2.0
  camera: ^0.10.5+7
  elementary: ^3.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  get_it: ^7.6.4
  image: ^3.3.0
  pedantic: ^1.11.1
  scidart: ^0.0.2-dev.12
  tflite_flutter: ^0.10.4
  tflite_flutter_helper_plus: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/

